version: '3'

vars:
  ANSIBLE_VM: vault-ansible
  VAULT_VM: vault-server
  AGENT_VM: vault-agent

tasks:
  # Main workflow tasks
  infrastructure:
    desc: Initialize infrastructure (VMs, certs, networking)
    cmds:
      - ./scripts/init.sh all
    silent: true

  vault-server:
    desc: Setup Vault server (requires infrastructure)
    cmds:
      - |
        if [[ ! -f "generated/vm-ips.env" ]]; then
          echo "[ERROR] Infrastructure not ready. Run 'task infrastructure' first."
          exit 1
        fi
      - ./scripts/server.sh all
    silent: true

  vault-ansible:
    desc: Setup Ansible with AppRole authentication (requires vault-server)
    cmds:
      - |
        if [[ ! -f "root-token.txt" ]]; then
          echo "[ERROR] Vault server not ready. Run 'task vault-server' first."
          exit 1
        fi
      - ./scripts/ansible.sh all
    silent: true

  vault-agent:
    desc: Setup Vault agent (requires vault-ansible)
    cmds:
      - |
        if [[ ! -f "generated/ansible-auth/role-id" ]]; then
          echo "[ERROR] Ansible not ready. Run 'task vault-ansible' first."
          exit 1
        fi
      - ./scripts/agent.sh all
    silent: true

  secrets:
    desc: Create demo secrets and agent policy (based on Agent/secret.tmpl)
    cmds:
      - |
        if [[ ! -f "root-token.txt" ]]; then
          echo "[ERROR] Vault server not ready. Run 'task vault-server' first."
          exit 1
        fi
      - ./scripts/secrets.sh all
    silent: true

  # Convenience task
  full-setup:
    desc: Complete lab setup (all components)
    cmds:
      - task: infrastructure
      - task: vault-server
      - task: vault-ansible
      - task: secrets
      - task: vault-agent
      - task: status
      - echo "[lab] Complete lab setup finished!"
    silent: true

  # Utility tasks
  clean:
    desc: Clean up VMs and generated files
    cmds:
      - bash -c "source ./scripts/common.sh && cleanup_vms"
    silent: true

  status:
    desc: Show lab environment status
    cmds:
      - ./scripts/utils.sh status

  # (Monitoring is installed automatically during vault-agent setup)
