#cloud-config
packages:
  - python3
  - python3-pip
  - openssh-client
  - curl
  - unzip
  - openssl
  - jq

runcmd:
  - pip3 install ansible hvac
  - ansible-galaxy collection install community.hashi_vault
  - |
    ARCH=$(uname -m)
    if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
      VAULT_ARCH="arm64"
    else
      VAULT_ARCH="amd64"
    fi
    curl -fsSL https://releases.hashicorp.com/vault/1.15.4/vault_1.15.4_linux_${VAULT_ARCH}.zip -o /tmp/vault.zip
  - unzip /tmp/vault.zip -d /tmp
  - sudo mv /tmp/vault /usr/local/bin/
  - rm /tmp/vault.zip
  - ssh-keygen -t rsa -b 2048 -f /home/ubuntu/.ssh/id_rsa -N ''
  - chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa*
  - sudo mkdir -p /opt/vault/certs
  - echo 'export PATH=$HOME/.local/bin:$PATH' >> /home/ubuntu/.bashrc
