#cloud-config
packages:
  - curl
  - unzip
  - python3
  - jq

runcmd:
  - |
    ARCH=$(uname -m)
    if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
      VAULT_ARCH="arm64"
    else
      VAULT_ARCH="amd64"
    fi
    curl -fsSL https://releases.hashicorp.com/vault/1.15.4/vault_1.15.4_linux_${VAULT_ARCH}.zip -o /tmp/vault.zip
  - unzip /tmp/vault.zip -d /tmp
  - sudo mv /tmp/vault /usr/local/bin/
  - rm /tmp/vault.zip
  - sudo useradd --system --home /opt/vault-agent --shell /bin/bash vault-agent
  - sudo mkdir -p /opt/vault-agent/auth
  - sudo mkdir -p /opt/vault-agent/config
  - sudo mkdir -p /opt/vault-agent/secrets
  - sudo mkdir -p /opt/vault-agent/templates
  - sudo mkdir -p /opt/vault-agent/bin
  - sudo mkdir -p /opt/vault-agent/backups
  - sudo mkdir -p /var/log/vault-agent
  - sudo mkdir -p /var/log/bf-app
  - sudo mkdir -p /opt/vault/certs
  - sudo chown -R vault-agent:vault-agent /opt/vault-agent /var/log/vault-agent /var/log/bf-app
