---
- name: "Generate wrapped Secret ID and deploy to Vault Agent hosts"
  hosts: localhost
  gather_facts: no
  vars_files:
    - lab-vars.yml

  tasks:
    - name: "Generate wrapped Secret ID"
      uri:
        url: "{{ vault_url }}/v1/auth/approle/role/{{ app_name }}/secret-id"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_admin_token }}"
          X-Vault-Wrap-TTL: "{{ wrap_ttl }}"
        body_format: json
        body: {}
        validate_certs: yes
      register: wrapped_secret

    - name: "Display wrapped token (for verification)"
      debug:
        msg: "Wrapped Token: {{ wrapped_secret.json.wrap_info.token }}"

    - name: "Store wrapped token metadata"
      set_fact:
        wrapped_token: "{{ wrapped_secret.json.wrap_info.token }}"
        wrap_creation_time: "{{ wrapped_secret.json.wrap_info.creation_time }}"
        wrap_ttl_seconds: "{{ wrapped_secret.json.wrap_info.ttl }}"

- name: "Deploy wrapped Secret ID to Vault Agent hosts"
  hosts: vault_agents
  become: yes
  gather_facts: no
  vars:
    app_name: "{{ app_name | default('myapp') }}"

  tasks:
    - name: "Create Vault Agent auth directory"
      file:
        path: "/opt/vault-agent/auth"
        state: directory
        mode: '0755'
        owner: vault-agent
        group: vault-agent

    - name: "Deploy wrapped Secret ID to agent host"
      copy:
        content: "{{ hostvars['localhost']['wrapped_token'] }}"
        dest: "/opt/vault-agent/auth/wrapped-secret-id"
        mode: '0600'
        owner: vault-agent
        group: vault-agent

    - name: "Create Secret ID metadata file"
      copy:
        content: |
          # Wrapped Secret ID Metadata
          # Generated: {{ hostvars['localhost']['wrap_creation_time'] }}
          # TTL: {{ hostvars['localhost']['wrap_ttl_seconds'] }} seconds
          # Application: {{ app_name }}
          # 
          # Use this command to unwrap:
          # vault unwrap $(cat /opt/vault-agent/auth/wrapped-secret-id)
        dest: "/opt/vault-agent/auth/.secret_id_metadata"
        mode: '0644'
        owner: vault-agent
        group: vault-agent

    - name: "Display result - Wrapped Secret ID deployed"
      debug:
        msg: "✅ Wrapped Secret ID has been deployed to {{ inventory_hostname }}"
